version: '3.8'

services:
  al-eats:
    image: php:8.1-apache
    container_name: al-eats
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./data:/var/www/html/data
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.al-eats.rule=Host(\`al-eats.local\`)"
      - "traefik.http.services.al-eats.loadbalancer.server.port=80"
